pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["adv.htm","Appendix &#62; Advanced Topics","Advanced Topics",""],
["adv_commandlineflags.htm","Appendix &#62; Advanced Topics &#62; Command-Line Flags for Sketchpad (Windows Version)","Command-Line Flags for Sketchpad (Windows Version)",""],
["adv_graphicsexport.htm","Appendix &#62; Advanced Topics &#62; Advanced Graphics Export","Advanced Graphics Export",""],
["adv_menustructure.htm","Appendix &#62; Advanced Topics &#62; Sketchpad&#39;s Menu Structure","Sketchpad’s Menu Structure",""],
["adv_sketchpadsmath.htm","Appendix &#62; Advanced Topics &#62; Sketchpad&#39;s Internal Mathematics","Sketchpad’s Internal Mathematics",""],
["adv_text.htm","Appendix &#62; Advanced Topics &#62; Advanced Text Topics","Advanced Text Topics",""],
["adv_text_lossy.htm","Appendix &#62; Advanced Topics &#62; Advanced Text Topics &#62; Unrecognized Text Format","Unrecognized Text Format",""],
["adv_tool.htm","Appendix &#62; Advanced Topics &#62; Advanced Tool Topics","Advanced Tool Topics",""],
["adv_tool_alttoolfolders.htm","Appendix &#62; Advanced Topics &#62; Advanced Tool Topics &#62; Alternate Tool Folders","Alternate Tool Folders",""],
["adv_tool_automatch.htm","Appendix &#62; Advanced Topics &#62; Advanced Tool Topics &#62; Automatically Match a Given Object","Automatically Match a Given Object",""],
["adv_tool_generatelabels.htm","Appendix &#62; Advanced Topics &#62; Advanced Tool Topics &#62; Generate Specific Labels","Generate Specific Labels",""],
["adv_tool_missing_given.htm","Appendix &#62; Advanced Topics &#62; Advanced Tool Topics &#62; Use a Custom Tool as a Custom Command","Use a Custom Tool as a Custom Command",""],
["angle_markers.htm","Objects &#62; Angle Markers and Tick Marks &#62; Angle Markers","Angle Markers",""],
["app.htm","Appendix","Appendix",""],
["app_constructionsandtechniq.htm","Appendix &#62; Special Constructions and Techniques","Special Constructions and Techniques",""],
["app_credits.htm","Appendix &#62; Credits","Credits",""],
["app_license.htm","Appendix &#62; License Agreement","License",""],
["app_techsupport.htm","Appendix &#62; Technical and Installation Support","Technical and Installation Support",""],
["caption-editing_keys.htm","Keyboard &#62; Caption-Editing Keys","Caption-Editing Keys",""],
["distance_units_across_platform.htm","Appendix &#62; Advanced Topics &#62; Distance Units Across Platforms","Distance Units Across Platforms",""],
["drag_objects.htm","Tools &#62; Arrow Tools &#62; Drag Objects","Drag Objects",""],
["gsp5_refctr_ftsearch.htm","No title","Contents | Index | Search Enter one or more keywords to search (&#39;*&#39; and &#39;?&#39; wildcards are supported): ",""],
["hot_text.htm","Objects &#62; Captions &#62; Hot Text&#8482;","Hot Text&#8482;",""],
["howto_bisectortool.htm","Tools &#62; Custom Tools &#62; How to Make a Perpendicular Bisector Tool","How to Make a Perpendicular Bisector Tool",""],
["howto_congruentangles.htm","Menus &#62; Transform Menu &#62; Rotate &#62; How to Construct Congruent Angles","How to Construct Congruent Angles",""],
["howto_congruentsegments.htm","Menus &#62; Construct Menu &#62; Circle by Center+Radius &#62; How to Construct Congruent Segments","How to Construct Congruent Segments",""],
["howto_fixedangle.htm","Menus &#62; Transform Menu &#62; Rotate &#62; How to Construct an Angle of Fixed Measure","How to Construct an Angle of Fixed Measure",""],
["howto_fixedlengthsegment.htm","Menus &#62; Construct Menu &#62; Circle by Center+Point &#62; How to Construct a Segment of Fixed Length","How to Construct a Segment of Fixed Length",""],
["howto_sierpinski.htm","Objects &#62; Iterations and Iterated Images &#62; How to Construct a Sierpiński Gasket","How to Construct a Sierpiński Gasket",""],
["howto_zoom.htm","Tools &#62; Arrow Tools &#62; How to Zoom In and Out on a Sketch","How to Zoom In and Out on a Sketch",""],
["importing_pictures.htm","Objects &#62; Pictures and Drawings &#62; Importing Pictures","Importing Pictures",""],
["increase_decrease_value.htm","Menus &#62; Context Menu &#62; Increase Value/Decrease Value","Increase Value/Decrease Value",""],
["increase_iter_decrease_iter.htm","Menus &#62; Context Menu &#62; Increase Iterations/Decrease Iterations","Increase Iterations/Decrease Iterations",""],
["increase_res_decrease_res.htm","Menus &#62; Context Menu &#62; Increase Resolution/Decrease Resolution","Increase Resolution/Decrease Resolution",""],
["jsp.htm","Appendix &#62; JavaSketchpad and Web-Based Dynamic Geometry","JavaSketchpad and Web-Based Dynamic Geometry",""],
["jsp_createjava.htm","Appendix &#62; JavaSketchpad and Web-Based Dynamic Geometry &#62; Create a JavaSketchpad Web Page","Create a JavaSketchpad Web Page",""],
["jsp_javafolder.htm","Appendix &#62; JavaSketchpad and Web-Based Dynamic Geometry &#62; Essential JavaSketchpad Folder Structure","Essential JavaSketchpad Folder Structure",""],
["jsp_modifyyourpages.htm","Appendix &#62; JavaSketchpad and Web-Based Dynamic Geometry &#62; Modify and Publish Your Pages","Modify and Publish Your Pages",""],
["jsp_weboverview.htm","Appendix &#62; JavaSketchpad and Web-Based Dynamic Geometry &#62; Web Publishing Overview","Web Publishing Overview",""],
["jsp_whatcangowrong.htm","Appendix &#62; JavaSketchpad and Web-Based Dynamic Geometry &#62; What Can Go Wrong","What Can Go Wrong",""],
["lg_public_license.htm","Appendix &#62; Credits &#62; LG Public License","LG Public License",""],
["license_information.htm","Menus &#62; Help Menu &#62; License Information","License Information",""],
["menus.htm","Menus","Menus",""],
["menus_construct.htm","Menus &#62; Construct Menu","Construct Menu",""],
["menus_construct_arc3points.htm","Menus &#62; Construct Menu &#62; Arc through 3 Points","Arc through 3 Points",""],
["menus_construct_arconcircle.htm","Menus &#62; Construct Menu &#62; Arc on Circle","Arc on Circle",""],
["menus_construct_bisector.htm","Menus &#62; Construct Menu &#62; Angle Bisector","Angle Bisector",""],
["menus_construct_circctrpt.htm","Menus &#62; Construct Menu &#62; Circle by Center+Point","Circle by Center+Point",""],
["menus_construct_circctrrad.htm","Menus &#62; Construct Menu &#62; Circle by Center+Radius","Circle by Center+Radius",""],
["menus_construct_int.htm","Menus &#62; Construct Menu &#62; Interior","Interior",""],
["menus_construct_int_circle.htm","Menus &#62; Construct Menu &#62; Interior &#62; Circle Interior","Circle Interior",""],
["menus_construct_int_poly.htm","Menus &#62; Construct Menu &#62; Interior &#62; Polygon Interior","Polygon Interior",""],
["menus_construct_int_sector.htm","Menus &#62; Construct Menu &#62; Interior &#62; Arc Sector","Arc Sector",""],
["menus_construct_int_segment.htm","Menus &#62; Construct Menu &#62; Interior &#62; Arc Segment","Arc Segment",""],
["menus_construct_intersect.htm","Menus &#62; Construct Menu &#62; Intersection","Intersection",""],
["menus_construct_locus.htm","Menus &#62; Construct Menu &#62; Locus","Locus",""],
["menus_construct_midpoint.htm","Menus &#62; Construct Menu &#62; Midpoint","Midpoint",""],
["menus_construct_parallel.htm","Menus &#62; Construct Menu &#62; Parallel Line","Parallel Line",""],
["menus_construct_perpendic.htm","Menus &#62; Construct Menu &#62; Perpendicular Line","Perpendicular Line",""],
["menus_construct_pointonobj.htm","Menus &#62; Construct Menu &#62; Point on Object","Point on Object",""],
["menus_construct_segment.htm","Menus &#62; Construct Menu &#62; Segment, Ray, and Line","Segment, Ray, and Line",""],
["menus_context.htm","Menus &#62; Context Menu","Context Menu",""],
["menus_context_frontback.htm","Menus &#62; Context Menu &#62; Bring to Front/Send to Back","Bring to Front/Send to Back",""],
["menus_display.htm","Menus &#62; Display Menu","Display Menu",""],
["menus_display_animate.htm","Menus &#62; Display Menu &#62; Animate","Animate",""],
["menus_display_color.htm","Menus &#62; Display Menu &#62; Color","Color",""],
["menus_display_color_other.htm","Menus &#62; Display Menu &#62; Color &#62; Other Color","Other Color",""],
["menus_display_color_param.htm","Menus &#62; Display Menu &#62; Color &#62; Parametric Color","Parametric Color",""],
["menus_display_erasetraces.htm","Menus &#62; Display Menu &#62; Erase Traces","Erase Traces",""],
["menus_display_hideobjects.htm","Menus &#62; Display Menu &#62; Hide Objects","Hide Objects",""],
["menus_display_incdecspeed.htm","Menus &#62; Display Menu &#62; Increase Speed/Decrease Speed","Increase Speed/Decrease Speed",""],
["menus_display_labelobjects.htm","Menus &#62; Display Menu &#62; Label Object","Label Object",""],
["menus_display_linestyle.htm","Menus &#62; Display Menu &#62; Line Style","Line Style",""],
["menus_display_motioncontrol.htm","Menus &#62; Display Menu &#62; Show/Hide Motion Controller","Show/Hide Motion Controller",""],
["menus_display_pointstyle.htm","Menus &#62; Display Menu &#62; Point Style","Point Style",""],
["menus_display_showallhidden.htm","Menus &#62; Display Menu &#62; Show All Hidden","Show All Hidden",""],
["menus_display_showhidelabel.htm","Menus &#62; Display Menu &#62; Show/Hide Labels","Show/Hide Labels",""],
["menus_display_stopanimation.htm","Menus &#62; Display Menu &#62; Stop Animation","Stop Animation",""],
["menus_display_text.htm","Menus &#62; Display Menu &#62; Text","Text",""],
["menus_display_textpalette.htm","Menus &#62; Display Menu &#62; Show/Hide Text Palette","Show/Hide Text Palette",""],
["menus_display_toolbox.htm","Menus &#62; Display Menu &#62; Show/Hide Toolbox","Show/Hide Toolbox",""],
["menus_display_trace.htm","Menus &#62; Display Menu &#62; Trace","Trace",""],
["menus_edit.htm","Menus &#62; Edit Menu","Edit Menu",""],
["menus_edit_btns.htm","Menus &#62; Edit Menu &#62; Action Buttons","Action Buttons",""],
["menus_edit_btns_animation.htm","Menus &#62; Edit Menu &#62; Action Buttons &#62; Animation","Animation",""],
["menus_edit_btns_hideshow.htm","Menus &#62; Edit Menu &#62; Action Buttons &#62; Hide/Show","Hide/Show",""],
["menus_edit_btns_link.htm","Menus &#62; Edit Menu &#62; Action Buttons &#62; Link","Link",""],
["menus_edit_btns_movement.htm","Menus &#62; Edit Menu &#62; Action Buttons &#62; Movement","Movement",""],
["menus_edit_btns_present.htm","Menus &#62; Edit Menu &#62; Action Buttons &#62; Presentation","Presentation",""],
["menus_edit_btns_scroll.htm","Menus &#62; Edit Menu &#62; Action Buttons &#62; Scroll","Scroll",""],
["menus_edit_btns_sound.htm","Menus &#62; Edit Menu &#62; Action Buttons &#62; Sound","Sound",""],
["menus_edit_clear.htm","Menus &#62; Edit Menu &#62; Clear","Clear",""],
["menus_edit_copy.htm","Menus &#62; Edit Menu &#62; Copy","Copy",""],
["menus_edit_croppicture.htm","Menus &#62; Edit Menu &#62; Crop Picture to Polygon","Crop Picture to Polygon",""],
["menus_edit_cut.htm","Menus &#62; Edit Menu &#62; Cut","Cut",""],
["menus_edit_editdefinition.htm","Menus &#62; Edit Menu &#62; Edit Definition","Edit Definition",""],
["menus_edit_paste.htm","Menus &#62; Edit Menu &#62; Paste","Paste",""],
["menus_edit_preferences.htm","Menus &#62; Edit Menu &#62; Preferences","Preferences",""],
["menus_edit_preferences_adv.htm","Menus &#62; Edit Menu &#62; Preferences &#62; Advanced Preferences","Advanced Preferences",""],
["menus_edit_properties.htm","Menus &#62; Edit Menu &#62; Properties","Properties",""],
["menus_edit_redo.htm","Menus &#62; Edit Menu &#62; Redo","Redo",""],
["menus_edit_selectall.htm","Menus &#62; Edit Menu &#62; Select All","Select All",""],
["menus_edit_selectchildren.htm","Menus &#62; Edit Menu &#62; Select Children","Select Children",""],
["menus_edit_selectparents.htm","Menus &#62; Edit Menu &#62; Select Parents","Select Parents",""],
["menus_edit_splitmerge.htm","Menus &#62; Edit Menu &#62; Split/Merge","Split/Merge",""],
["menus_edit_undo.htm","Menus &#62; Edit Menu &#62; Undo","Undo",""],
["menus_file.htm","Menus &#62; File Menu","File Menu",""],
["menus_file_close.htm","Menus &#62; File Menu &#62; Close","Close",""],
["menus_file_documentoptions.htm","Menus &#62; File Menu &#62; Document Options","Document Options",""],
["menus_file_newsketch.htm","Menus &#62; File Menu &#62; New Sketch","New Sketch",""],
["menus_file_open.htm","Menus &#62; File Menu &#62; Open","Open",""],
["menus_file_open_sketchexchange.htm","Menus &#62; File Menu &#62; Sketchpad Sketch Exchange","Sketchpad Sketch Exchange",""],
["menus_file_open_sll.htm","Menus &#62; File Menu &#62; Sketchpad LessonLink","Sketchpad LessonLink",""],
["menus_file_pagesetup.htm","Menus &#62; File Menu &#62; Page Setup","Page Setup",""],
["menus_file_print.htm","Menus &#62; File Menu &#62; Print","Print",""],
["menus_file_printpreview.htm","Menus &#62; File Menu &#62; Print Preview","Print Preview",""],
["menus_file_quit.htm","Menus &#62; File Menu &#62; Quit","Quit",""],
["menus_file_save.htm","Menus &#62; File Menu &#62; Save","Save",""],
["menus_file_saveas.htm","Menus &#62; File Menu &#62; Save As","Save As",""],
["menus_graph.htm","Menus &#62; Graph Menu","Graph Menu",""],
["menus_graph_definecoordsys.htm","Menus &#62; Graph Menu &#62; Define Coordinate System","Define Coordinate System",""],
["menus_graph_derivative.htm","Menus &#62; Number Menu &#62; Define Derivative Function","Define Derivative Function",""],
["menus_graph_dotted_grid.htm","Menus &#62; Graph Menu &#62; Dotted Grid","Dotted Grid",""],
["menus_graph_gridform.htm","Menus &#62; Graph Menu &#62; Grid Form","Grid Form",""],
["menus_graph_markcoordsystem.htm","Menus &#62; Graph Menu &#62; Mark Coordinate System","Mark Coordinate System",""],
["menus_graph_newfunction.htm","Menus &#62; Number Menu &#62; New Function","New Function",""],
["menus_graph_plotcurve.htm","Menus &#62; Graph Menu &#62; Plot Parametric Curve","Plot Parametric Curve",""],
["menus_graph_plotfunction.htm","Menus &#62; Graph Menu &#62; Plot Function/Plot New Function","Plot Function/Plot New Function",""],
["menus_graph_plotpoints.htm","Menus &#62; Graph Menu &#62; Plot Points/Plot as (x, y)/Plot as (r, θ)","Plot Points/Plot as (x, y)/Plot as (r, θ)",""],
["menus_graph_plottabledata.htm","Menus &#62; Graph Menu &#62; Plot Table Data","Plot Table Data",""],
["menus_graph_plotvalue.htm","Menus &#62; Graph Menu &#62; Plot Value on Axis","Plot Value on Axis",""],
["menus_graph_showgrid.htm","Menus &#62; Graph Menu &#62; Show Grid","Show Grid",""],
["menus_graph_snappoints.htm","Menus &#62; Graph Menu &#62; Snap Points","Snap Points",""],
["menus_help.htm","Menus &#62; Help Menu","Help Menu",""],
["menus_measure.htm","Menus &#62; Measure Menu","Measure Menu",""],
["menus_measure_abscissa.htm","Menus &#62; Measure Menu &#62; Abscissa (x) / Polar Distance (r)","Abscissa (x) / Polar Distance (r)",""],
["menus_measure_angle.htm","Menus &#62; Measure Menu &#62; Angle","Angle",""],
["menus_measure_arcangle.htm","Menus &#62; Measure Menu &#62; Arc Angle","Arc Angle",""],
["menus_measure_arclength.htm","Menus &#62; Measure Menu &#62; Arc Length","Arc Length",""],
["menus_measure_area.htm","Menus &#62; Measure Menu &#62; Area","Area",""],
["menus_measure_circumference.htm","Menus &#62; Measure Menu &#62; Circumference","Circumference",""],
["menus_measure_coorddist.htm","Menus &#62; Measure Menu &#62; Coordinate Distance","Coordinate Distance",""],
["menus_measure_coordinates.htm","Menus &#62; Measure Menu &#62; Coordinates","Coordinates",""],
["menus_measure_distance.htm","Menus &#62; Measure Menu &#62; Distance","Distance",""],
["menus_measure_equation.htm","Menus &#62; Measure Menu &#62; Equation","Equation",""],
["menus_measure_length.htm","Menus &#62; Measure Menu &#62; Length","Length",""],
["menus_measure_ordinate.htm","Menus &#62; Measure Menu &#62; Ordinate (y) / Polar Direction (θ)","Ordinate (y) / Polar Direction (θ)",""],
["menus_measure_perimeter.htm","Menus &#62; Measure Menu &#62; Perimeter","Perimeter",""],
["menus_measure_radius.htm","Menus &#62; Measure Menu &#62; Radius","Radius",""],
["menus_measure_ratio.htm","Menus &#62; Measure Menu &#62; Ratio","Ratio",""],
["menus_measure_slope.htm","Menus &#62; Measure Menu &#62; Slope","Slope",""],
["menus_measure_valueofpoint.htm","Menus &#62; Measure Menu &#62; Value of Point","Value of Point",""],
["menus_number.htm","Menus &#62; Number Menu","Number Menu",""],
["menus_number_addtabledata.htm","Menus &#62; Number Menu &#62; Add Table Data","Add Table Data",""],
["menus_number_calculate.htm","Menus &#62; Number Menu &#62; Calculate","Calculate",""],
["menus_number_deffndrawing.htm","Menus &#62; Number Menu &#62; Define Function from Drawing or Picture","Define Function from Drawing or Picture",""],
["menus_number_newparameter.htm","Menus &#62; Number Menu &#62; New Parameter","New Parameter",""],
["menus_number_removetbldata.htm","Menus &#62; Number Menu &#62; Remove Table Data","Remove Table Data",""],
["menus_number_tabulate.htm","Menus &#62; Number Menu &#62; Tabulate","Tabulate",""],
["menus_trans.htm","Menus &#62; Transform Menu","Transform Menu",""],
["menus_trans_custdefine.htm","Menus &#62; Transform Menu &#62; Define Custom Transform","Define Custom Transform",""],
["menus_trans_custedit.htm","Menus &#62; Transform Menu &#62; Edit Custom Transforms","Edit Custom Transforms",""],
["menus_trans_dilate.htm","Menus &#62; Transform Menu &#62; Dilate","Dilate",""],
["menus_trans_iter.htm","Menus &#62; Transform Menu &#62; Iterate","Iterate",""],
["menus_trans_iter_multmaps.htm","Menus &#62; Transform Menu &#62; Iterate &#62; Multiple Iteration Maps","Multiple Iteration Maps",""],
["menus_trans_iter_usedialog.htm","Menus &#62; Transform Menu &#62; Iterate &#62; Using the Iterate Dialog Box","Using the Iterate Dialog Box",""],
["menus_trans_mark.htm","Menus &#62; Transform Menu &#62; Mark Commands","Mark Commands",""],
["menus_trans_markangle.htm","Menus &#62; Transform Menu &#62; Mark Angle","Mark Angle",""],
["menus_trans_markcenter.htm","Menus &#62; Transform Menu &#62; Mark Center","Mark Center",""],
["menus_trans_markdistance.htm","Menus &#62; Transform Menu &#62; Mark Distance","Mark Distance",""],
["menus_trans_markmirror.htm","Menus &#62; Transform Menu &#62; Mark Mirror","Mark Mirror",""],
["menus_trans_markratio.htm","Menus &#62; Transform Menu &#62; Mark Ratio/Mark Segment Ratio/Mark Scale Factor","Mark Ratio/Mark Segment Ratio/Mark Scale Factor",""],
["menus_trans_markvector.htm","Menus &#62; Transform Menu &#62; Mark Vector","Mark Vector",""],
["menus_trans_reflect.htm","Menus &#62; Transform Menu &#62; Reflect","Reflect",""],
["menus_trans_rotate.htm","Menus &#62; Transform Menu &#62; Rotate","Rotate",""],
["menus_trans_translate.htm","Menus &#62; Transform Menu &#62; Translate","Translate",""],
["menus_trans_translate_mrked.htm","Menus &#62; Transform Menu &#62; Translate &#62; Marked Translation Vector","Marked Translation Vector",""],
["menus_trans_translate_polar.htm","Menus &#62; Transform Menu &#62; Translate &#62; Polar Translation Vector","Polar Translation Vector",""],
["menus_trans_translate_rect.htm","Menus &#62; Transform Menu &#62; Translate &#62; Rectangular Translation Vector","Rectangular Translation Vector",""],
["menus_window.htm","Menus &#62; Window Menu","Window Menu",""],
["object_parametriccurve.htm","Objects &#62; Parametric Plots","Parametric Plots",""],
["objects.htm","Objects","Objects",""],
["objects_arcs.htm","Objects &#62; Arcs","Arcs",""],
["objects_attrib.htm","Objects &#62; Common Object Attributes","Common Object Attributes",""],
["objects_attrib_display.htm","Objects &#62; Common Object Attributes &#62; Display Attributes","Display Attributes",""],
["objects_attrib_labelprops.htm","Objects &#62; Common Object Attributes &#62; Label Properties","Label Properties",""],
["objects_attrib_labels.htm","Objects &#62; Common Object Attributes &#62; Object Labels","Object Labels",""],
["objects_attrib_props.htm","Objects &#62; Common Object Attributes &#62; Object Properties","Object Properties",""],
["objects_attrib_relations.htm","Objects &#62; Common Object Attributes &#62; Parent-Child Relationships","Parent-Child Relationships",""],
["objects_btns.htm","Objects &#62; Action Buttons","Action Buttons",""],
["objects_btns_animateprops.htm","Objects &#62; Action Buttons &#62; Animation Buttons and Properties","Animation Buttons and Properties",""],
["objects_btns_hideshowprops.htm","Objects &#62; Action Buttons &#62; Hide/Show Buttons and Properties","Hide/Show Buttons and Properties",""],
["objects_btns_linkprops.htm","Objects &#62; Action Buttons &#62; Link Buttons and Properties","Link Buttons and Properties",""],
["objects_btns_moveprops.htm","Objects &#62; Action Buttons &#62; Movement Buttons and Properties","Movement Buttons and Properties",""],
["objects_btns_presentprops.htm","Objects &#62; Action Buttons &#62; Presentation Buttons and Properties","Presentation Buttons and Properties",""],
["objects_btns_scrollprops.htm","Objects &#62; Action Buttons &#62; Scroll Buttons and Properties","Scroll Buttons and Properties",""],
["objects_calculations.htm","Objects &#62; Calculations","Calculations",""],
["objects_captions.htm","Objects &#62; Captions","Captions",""],
["objects_cat_plot_sampledpic.htm","Objects &#62; Object Categories &#62; Plots and Sampled Objects &#62; Plot Properties for a Sampled Transformed Picture","Plot Properties for a Sampled Transformed Picture",""],
["objects_cats.htm","Objects &#62; Object Categories","Object Categories",""],
["objects_cats_layered.htm","Objects &#62; Object Categories &#62; Layered Objects","Layered Objects",""],
["objects_cats_opacity_props.htm","Objects &#62; Object Categories &#62; Translucent Objects &#62; Opacity Properties","Opacity Properties",""],
["objects_cats_paths.htm","Objects &#62; Object Categories &#62; Path Objects","Path Objects",""],
["objects_cats_plot_fnprops.htm","Objects &#62; Object Categories &#62; Plots and Sampled Objects &#62; Plot Properties for a Function Plot or Parametric Plot","Plot Properties for a Function Plot or Parametric Plot",""],
["objects_cats_plot_locprops.htm","Objects &#62; Object Categories &#62; Plots and Sampled Objects &#62; Plot Properties for a Locus or Sampled Transformed Path","Plot Properties for a Locus or Sampled Transformed Path",""],
["objects_cats_plots.htm","Objects &#62; Object Categories &#62; Plots and Sampled Objects","Plots and Sampled Objects",""],
["objects_cats_straight.htm","Objects &#62; Object Categories &#62; Straight Objects","Straight Objects",""],
["objects_cats_text.htm","Objects &#62; Object Categories &#62; Text Objects","Text Objects",""],
["objects_cats_values.htm","Objects &#62; Object Categories &#62; Values","Values",""],
["objects_cats_values_props.htm","Objects &#62; Object Categories &#62; Values &#62; Value Properties","Value Properties",""],
["objects_circles.htm","Objects &#62; Circles","Circles",""],
["objects_coordsys.htm","Objects &#62; Coordinate Systems and Axes","Coordinate Systems and Axes",""],
["objects_coordsys_axisprops.htm","Objects &#62; Coordinate Systems and Axes &#62; Axis Properties","Axis Properties",""],
["objects_coordsys_multiple.htm","Objects &#62; Coordinate Systems and Axes &#62; Multiple Coordinate Systems","Multiple Coordinate Systems",""],
["objects_functionplots.htm","Objects &#62; Function Plots","Function Plots",""],
["objects_functions.htm","Objects &#62; Functions","Functions",""],
["objects_functions_ddfprops.htm","Objects &#62; Functions &#62; Data-Defined Function Properties","Data-Defined Function Properties",""],
["objects_iter.htm","Objects &#62; Iterations and Iterated Images","Iterations and Iterated Images",""],
["objects_iter_geometric.htm","Objects &#62; Iterations and Iterated Images &#62; A Geometric Iteration","A Geometric Iteration",""],
["objects_iter_numeric.htm","Objects &#62; Iterations and Iterated Images &#62; A Numeric Iteration","A Numeric Iteration",""],
["objects_iter_props.htm","Objects &#62; Iterations and Iterated Images &#62; Iteration Properties","Iteration Properties",""],
["objects_iter_working.htm","Objects &#62; Iterations and Iterated Images &#62; Working with Iterations","Working with Iterations",""],
["objects_loci.htm","Objects &#62; Loci","Loci",""],
["objects_loci_anatomy.htm","Objects &#62; Loci &#62; Anatomy of a Locus","Anatomy of a Locus",""],
["objects_markers.htm","Objects &#62; Angle Markers and Tick Marks","Angle Markers and Tick Marks",""],
["objects_markers_props.htm","Objects &#62; Angle Markers and Tick Marks &#62; Marker Properties","Marker Properties",""],
["objects_measurements.htm","Objects &#62; Measurements","Measurements",""],
["objects_parameters.htm","Objects &#62; Parameters","Parameters",""],
["objects_parameters_props.htm","Objects &#62; Parameters &#62; Parameter Properties","Parameter Properties",""],
["objects_pictures.htm","Objects &#62; Pictures and Drawings","Pictures and Drawings",""],
["objects_points.htm","Objects &#62; Points","Points",""],
["objects_polygonsinteriors.htm","Objects &#62; Polygons and Other Interiors","Polygons and Other Interiors",""],
["objects_segmentsrayslines.htm","Objects &#62; Segments, Rays, and Lines","Segments, Rays, and Lines",""],
["objects_tables.htm","Objects &#62; Tables","Tables",""],
["objects_tables_props.htm","Objects &#62; Tables &#62; Table Properties","Table Properties",""],
["opening_remote_documents.htm","Appendix &#62; Advanced Topics &#62; Opening Remote Documents","Opening Remote Documents",""],
["shortcuts.htm","Keyboard","Keyboard",""],
["shortcuts_howto_geoboard.htm","Objects &#62; Coordinate Systems and Axes &#62; How to Construct a Geoboard","How to Construct a Geoboard",""],
["shortcuts_howto_showjustone.htm","Menus &#62; Display Menu &#62; Show All Hidden &#62; How to Show Just One Hidden Object","How to Show Just One Hidden Object",""],
["shortcuts_howto_signum.htm","Windows &#62; Calculator &#62; How to Use Signum to Construct a Piecewise Function","How to Use Signum to Construct a Piecewise Function",""],
["shortcuts_howto_slider.htm","Menus &#62; Measure Menu &#62; Value of Point &#62; How to Construct a Slider","How to Construct a Slider",""],
["shortcuts_howto_splitmerge.htm","Menus &#62; Edit Menu &#62; Split/Merge &#62; How to Use Split and Merge to Explore Constructions","How to Use Split and Merge to Explore Constructions",""],
["shortcuts_specialkeys.htm","Keyboard &#62; Special Keys","Special Keys",""],
["sketchpad_explorer.htm","What&#39;s New &#62; Sketchpad Explorer","Sketchpad Explorer",""],
["sketchpadreference.htm","Sketchpad Reference","Sketchpad Reference",""],
["sound_buttons.htm","Objects &#62; Action Buttons &#62; Sound Buttons","Sound Buttons",""],
["tick_markers.htm","Objects &#62; Angle Markers and Tick Marks &#62; Tick Marks","Tick Marks",""],
["tools.htm","Tools","Tools",""],
["tools_arrow.htm","Tools &#62; Arrow Tools","Arrow Tools",""],
["tools_arrow_otheractions.htm","Tools &#62; Arrow Tools &#62; Other Arrow Actions","Other Arrow Actions",""],
["tools_arrow_selectdeselect.htm","Tools &#62; Arrow Tools &#62; Select and Deselect Objects","Select and Deselect Objects",""],
["tools_compass.htm","Tools &#62; Compass Tool","Compass Tool",""],
["tools_cust.htm","Tools &#62; Custom Tools","Custom Tools",""],
["tools_cust_making.htm","Tools &#62; Custom Tools &#62; Make a Custom Tool","Make a Custom Tool",""],
["tools_cust_menu.htm","Tools &#62; Custom Tools &#62; Custom Tools Menu","Custom Tools Menu",""],
["tools_cust_toolfolder.htm","Tools &#62; Custom Tools &#62; The Tool Folder","The Tool Folder",""],
["tools_cust_using.htm","Tools &#62; Custom Tools &#62; Use a Custom Tool","Use a Custom Tool",""],
["tools_marker.htm","Tools &#62; Marker Tool","Marker Tool",""],
["tools_objectinformation.htm","Tools &#62; Information Tool","Information Tool",""],
["tools_point.htm","Tools &#62; Point Tool","Point Tool",""],
["tools_polygon.htm","Tools &#62; Polygon Tools","Polygon Tools",""],
["tools_straight.htm","Tools &#62; Straightedge Tools","Straightedge Tools",""],
["tools_text.htm","Tools &#62; Text Tool","Text Tool",""],
["transforming_pictures.htm","Objects &#62; Pictures and Drawings &#62; Transforming Pictures","Transforming Pictures",""],
["translucent_objects.htm","Objects &#62; Object Categories &#62; Translucent Objects","Translucent Objects",""],
["unicode.htm","Appendix &#62; Advanced Topics &#62; Advanced Text Topics &#62; Unicode","Unicode",""],
["using_functions.htm","Objects &#62; Functions &#62; Using Functions","Using Functions",""],
["whatsnew.htm","What&#39;s New","What’s New",""],
["whatsnew_newfeatures.htm","What&#39;s New &#62; New Features in Version 5","New Features in Version 5",""],
["whatsnew_sampledocs.htm","What&#39;s New &#62; Sample Documents","Sample Documents",""],
["whatsnew_since500.htm","What&#39;s New &#62; Changes Since Release 5.00","Changes Since Release 5.00",""],
["whatsnew_v4users_reusework.htm","What&#39;s New &#62; Reusing Your Version 4 Work","Reusing Your Version 4 Work",""],
["windows.htm","Windows","Windows",""],
["windows_advprefs.htm","Windows &#62; Advanced Preferences","Advanced Preferences",""],
["windows_advprefs_editclrmac.htm","Windows &#62; Advanced Preferences &#62; Edit the Color Menu for Macintosh","Edit the Color Menu for Macintosh",""],
["windows_advprefs_editclrwin.htm","Windows &#62; Advanced Preferences &#62; Edit the Color Menu for Windows","Edit the Color Menu for Windows",""],
["windows_advprefs_export.htm","Windows &#62; Advanced Preferences &#62; Export Preferences","Export Preferences",""],
["windows_advprefs_sampling.htm","Windows &#62; Advanced Preferences &#62; Sampling Preferences","Sampling Preferences",""],
["windows_advprefs_system.htm","Windows &#62; Advanced Preferences &#62; System Preferences","System Preferences",""],
["windows_calculator.htm","Windows &#62; Calculator","Calculator",""],
["windows_calculator_parts.htm","Windows &#62; Calculator &#62; Parts of the Calculator","Parts of the Calculator",""],
["windows_colorpicker.htm","Windows &#62; Color Picker","Color Picker",""],
["windows_colorpicker_mac.htm","Windows &#62; Color Picker &#62; Macintosh Color Picker","Macintosh Color Picker",""],
["windows_colorpicker_win.htm","Windows &#62; Color Picker &#62; Windows Color Picker","Windows Color Picker",""],
["windows_docs.htm","Windows &#62; Documents","Documents",""],
["windows_docs_docoptions.htm","Windows &#62; Documents &#62; Document Options and Tool Options","Document Options and Tool Options",""],
["windows_docs_docwindows.htm","Windows &#62; Documents &#62; Document Windows","Document Windows",""],
["windows_motctrl.htm","Windows &#62; Motion Controller","Motion Controller",""],
["windows_motctrl_animprinc.htm","Windows &#62; Motion Controller &#62; Principles of Animation","Principles of Animation",""],
["windows_motctrl_parts.htm","Windows &#62; Motion Controller &#62; Parts of the Motion Controller","Parts of the Motion Controller",""],
["windows_motctrl_using.htm","Windows &#62; Motion Controller &#62; Using the Motion Controller","Using the Motion Controller",""],
["windows_prefs.htm","Windows &#62; Preferences","Preferences",""],
["windows_prefs_color.htm","Windows &#62; Preferences &#62; Color Preferences","Color Preferences",""],
["windows_prefs_precision.htm","Windows &#62; Preferences &#62; User Tip: Accuracy vs. Precision","User Tip: Accuracy vs. Precision",""],
["windows_prefs_text.htm","Windows &#62; Preferences &#62; Text Preferences","Text Preferences",""],
["windows_prefs_textstyle.htm","Windows &#62; Preferences &#62; Text Preferences &#62; Text Style Preferences","Text Style Preferences",""],
["windows_prefs_tools.htm","Windows &#62; Preferences &#62; Tools Preferences","Tools Preferences",""],
["windows_prefs_units.htm","Windows &#62; Preferences &#62; Units Preferences","Units Preferences",""],
["windows_properties.htm","Windows &#62; Properties","Properties",""],
["windows_script.htm","Windows &#62; Script View","Script View",""],
["windows_script_apply.htm","Windows &#62; Script View &#62; Apply the Script View Step-by-Step","Apply the Script View Step-by-Step",""],
["windows_script_givenssteps.htm","Windows &#62; Script View &#62; Givens and Steps of a Tool","Givens and Steps of a Tool",""],
["windows_txtpal.htm","Windows &#62; Text Palette","Text Palette",""],
["windows_txtpal_mathnotation.htm","Windows &#62; Text Palette &#62; Using Mathematical Notation in a Caption","Using Mathematical Notation in a Caption",""],
["windows_txtpal_using.htm","Windows &#62; Text Palette &#62; Using the Text Palette","Using the Text Palette",""],
["working_with_pictures.htm","Objects &#62; Pictures and Drawings &#62; Working with Pictures and Drawings","Working with Pictures and Drawings",""]];
