   toc1 = 
               '<table id="CsEmdPlr">'
             + '   <tr>'
             + '      <td class="top_center_clr">'
             + '         <div class="contentWrapper_left">'
             + '            <div class="content_left">'
             + '               <img src="$MediaDirectory$#images/top_left_corner.jpg" alt=" " class="borderTL" />'
             + '               <img src="$MediaDirectory$#images/top_right_corner.jpg" alt=" " class="borderTR" />'
             + '               <div id="$LinkDivID" class="indexlinks"><br/>'
             + '                  <h3>$VideoTitle</h3>'
$IndexLinks
             + '               </div>'
             + '            </div>'
             + '         </div>'
             + '         <div id="menuBottom"></div>'
             + '      </td>'
             + '      <td class="top_center">'
             + '         <div class="contentWrapper">'
             + '            <div class="content">'
             + '               <img src="$MediaDirectory$#images/top_left_corner.jpg" alt=" " class="borderTL" />'
             + '               <img src="$MediaDirectory$#images/top_right_corner.jpg" alt=" " class="borderTR" /><br/><br/>';          

   toc2 = 
               '               <br/> $AVICodecLink $QuicktimeLink'
             + '            </div>'
             + '         </div>'
             + '      </td>'
             + '   </tr>'
             + '   <tr>'
             + '      <td></td>'
             + '      <td class="bottom_center">'
             + '         <div class="contentWrapper">'
             + '            <div class="content">'
             + '               <img src="$MediaDirectory$#images/bottom_left.jpg" alt=" " class="borderBL"  />'
             + '               <img src="$MediaDirectory$#images/bottom_right.jpg" alt=" " class="borderBR" />'
             + '             </div>'
             + '         </div>'
             + '      </td>'
             + '   </tr>'
             + '</table>';